const canvas=document.querySelector('canvas'),status=document.querySelector('#status');
const bytes=await (await fetch('/model-review/user-head.glb')).arrayBuffer(),dv=new DataView(bytes),n=dv.getUint32(12,true),json=JSON.parse(new TextDecoder().decode(new Uint8Array(bytes,20,n))),base=28+n;
function read(index,dim){const a=json.accessors[index],v=json.bufferViews[a.bufferView],size=a.componentType===5126?4:2,o=base+(v.byteOffset||0)+(a.byteOffset||0),step=v.byteStride||dim*size,out=new Float32Array(a.count*dim);for(let i=0;i<a.count;i++)for(let j=0;j<dim;j++)out[i*dim+j]=size===4?dv.getFloat32(o+i*step+j*size,true):dv.getUint16(o+i*step+j*size,true);return out;}
const prim=json.meshes[0].primitives[0],positions=read(prim.attributes.POSITION,3),normals=read(prim.attributes.NORMAL,3),uv=read(prim.attributes.TEXCOORD_0,2),indices=Uint16Array.from(read(prim.indices,1));
const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<positions.length;i++){min[i%3]=Math.min(min[i%3],positions[i]);max[i%3]=Math.max(max[i%3],positions[i]);}const size=Math.max(...max.map((v,i)=>v-min[i]));for(let i=0;i<positions.length;i++)positions[i]=(positions[i]-(min[i%3]+max[i%3])*.5)/size;
const gl=canvas.getContext('webgl',{alpha:false,antialias:true});if(!gl)throw new Error('WebGL 不可用');
function shader(type,code){const s=gl.createShader(type);gl.shaderSource(s,code);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s;}
const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,`attribute vec3 aPosition,aNormal;attribute vec2 aUV;uniform float uYaw,uPitch,uAspect,uZoom;varying vec2 vUV;varying vec3 vNormal;void main(){float c=cos(uYaw),s=sin(uYaw),cp=cos(uPitch),sp=sin(uPitch);mat3 y=mat3(c,0.,-s,0.,1.,0.,s,0.,c),x=mat3(1.,0.,0.,0.,cp,sp,0.,-sp,cp);vec3 v=x*y*aPosition;v.z-=uZoom;gl_Position=vec4(v.x*2.75/uAspect,v.y*2.75,-1.0033389*v.z-.1001669,-v.z);vNormal=x*y*aNormal;vUV=aUV;}`));
gl.attachShader(p,shader(gl.FRAGMENT_SHADER,`precision mediump float;uniform sampler2D uTexture;uniform float uSolid;varying vec2 vUV;varying vec3 vNormal;void main(){float light=.38+.62*max(0.,dot(normalize(vNormal),normalize(vec3(-.5,.8,1.))));vec3 c=mix(texture2D(uTexture,vUV).rgb,vec3(.66,.7,.72)*light,uSolid);gl_FragColor=vec4(c,1.);}`));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));gl.useProgram(p);gl.enable(gl.DEPTH_TEST);
for(const [name,data,dim]of [['aPosition',positions,3],['aNormal',normals,3],['aUV',uv,2]]){const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);const a=gl.getAttribLocation(p,name);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,dim,gl.FLOAT,false,0,0);}const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,indices,gl.STATIC_DRAW);
const img=new Image();img.src='/model-review/basecolor.jpg';await img.decode();const tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,img);for(const q of [gl.TEXTURE_MIN_FILTER,gl.TEXTURE_MAG_FILTER])gl.texParameteri(gl.TEXTURE_2D,q,gl.LINEAR);for(const q of [gl.TEXTURE_WRAP_S,gl.TEXTURE_WRAP_T])gl.texParameteri(gl.TEXTURE_2D,q,gl.CLAMP_TO_EDGE);
let yaw=-Math.PI/2,pitch=0,zoom=1.8,solid=0;const u={};for(const key of ['uYaw','uPitch','uAspect','uZoom','uSolid'])u[key]=gl.getUniformLocation(p,key);
function render(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2),w=Math.round(r.width*dpr),h=Math.round(r.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clearColor(.86,.86,.83,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.uniform1f(u.uYaw,yaw);gl.uniform1f(u.uPitch,pitch);gl.uniform1f(u.uAspect,w/h);gl.uniform1f(u.uZoom,zoom);gl.uniform1f(u.uSolid,solid);gl.drawElements(gl.TRIANGLES,indices.length,gl.UNSIGNED_SHORT,0);status.textContent=`5,174 个三角面 · 3,324 个导出顶点 · 1 材质 · 512×512 贴图 · 朝向 ${Math.round(yaw*180/Math.PI)}°`;}
for(const [id,a,b]of [['front',-Math.PI/2,0],['side',0,0],['back',Math.PI/2,0],['top',-Math.PI/2,Math.PI/2]])document.getElementById(id).onclick=()=>{yaw=a;pitch=b;render();};
for(const [id,value]of [['texture',0],['solid',1]])document.getElementById(id).onclick=()=>{solid=value;document.getElementById('texture').setAttribute('aria-pressed',String(!solid));document.getElementById('solid').setAttribute('aria-pressed',String(!!solid));render();};
let pointer=null,x=0,y=0;canvas.onpointerdown=e=>{if(pointer!==null)return;pointer=e.pointerId;x=e.clientX;y=e.clientY;canvas.setPointerCapture(pointer);};canvas.onpointermove=e=>{if(pointer!==e.pointerId)return;yaw+=(e.clientX-x)*.009;pitch=Math.max(-Math.PI/2,Math.min(Math.PI/2,pitch+(e.clientY-y)*.009));x=e.clientX;y=e.clientY;render();};for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,()=>pointer=null);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.9,Math.min(3,zoom+e.deltaY*.001));render();},{passive:false});new ResizeObserver(render).observe(canvas);render();
